---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: No action after apt-package-has-been-changed
  ansible.builtin.meta: noop
  listen: apt-package-has-been-changed
